### PR TITLE
RD-913: Add Menu button

### PR DESCRIPTION
**Pull request by danny-dang**
https://user-images.githubusercontent.com/47047158/221047619-146f2f0d-bc9b-410b-807d-40222f987d21.mp4

### CODE REVIEW

**Review by thellimist — APPROVED** [review]
Does it work when dropdown is 
1. near bottom of screen
2. near left/right of screen
3. smaller screens

**Comment by danny-dang** [comment]
@thellimist 
Updated. The menu will calculate the position of the Toggle Button to display the dropdown 
https://user-images.githubusercontent.com/47047158/221368887-60aa0d3e-86e5-4a15-ad1b-7c0e503c8a65.mp4

**Comment by thellimist** [comment]
I couldn't find the figma, but shouldn't there be a [gap](https://cdn.zappy.app/ab5de002733ce63b2fe886022e98f3fb.png) like this between the button and dropdown?

**Review by thellimist — APPROVED** [review]

**Comment by danny-dang** [comment]
Added a gap between the Butotn and Dropdown
image

**Pull request merged**
